import{i as p,a as f}from"./assets/vendor-uumJaN6-.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();function m(e){e.forEach(t=>{t.style.marginTop="15px"})}function a(e){e.disabled?e.disabled=!1:e.disabled=!0}function d(e){p.error({message:e,position:"topRight"})}const y="AIzaSyCDg8YNpb_-7aAum3KjZ3dvcD0ZALEWH48",g="https://www.googleapis.com/youtube/v3/search";async function h(e){try{return(await f.get(g,{params:{q:e,key:y,maxResults:10,perPage:10,type:"video",part:"snippet"}})).data}catch(t){console.log(t),d("Opps... Something went wrong. Try again later.")}}function v(e,t){const s=t.map(({id:{videoId:i},snippet:{title:r,channelTitle:o,thumbnails:{medium:{url:n}}}})=>`
    <li class="video-card">
      <a href="https://www.youtube.com/watch?v=${i}" target="_blank">
        <img class="video-img" src="${n}" alt="${r}">
      </a>
        <h3 class="video-text">${w(r,30)}</h3>
        <p class="video-text">${o}</p>
    </li>
  `).join("");e.insertAdjacentHTML("beforeend",s)}function w(e,t=100){return e.length>t?e.slice(0,t)+"...":e}function E(e){e.innerHTML=""}const b=document.querySelector(".form"),L=document.querySelector(".search-input"),l=document.querySelector(".search-btn"),u=document.querySelector(".video-list"),S=document.querySelectorAll(".container");let c="";b.addEventListener("submit",A);async function A(e){if(e.preventDefault(),a(l),c=L.value.trim(),!c){d("Empty querry!");return}E(u);try{m(S);const t=await h(c);console.log(t),v(u,t.items)}catch(t){alert("Opps... Something went wrong. Try again later."),console.log(t)}finally{a(l)}}
//# sourceMappingURL=index.js.map
