import{i as f,a as m}from"./assets/vendor-uumJaN6-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();function g(e){e.forEach(r=>{r.style.marginTop="15px"})}function a(e){e.disabled?e.disabled=!1:e.disabled=!0}function p(e){f.error({message:e,position:"topRight"})}const y="AIzaSyCDg8YNpb_-7aAum3KjZ3dvcD0ZALEWH48",h="https://www.googleapis.com/youtube/v3/search";async function v(e,r=1){try{return(await m.get(h,{params:{q:e,page:r,key:y,maxResults:12,perPage:12,type:"video",part:"snippet"}})).data}catch(n){console.log(n),p("Opps... Something went wrong. Try again later.")}}function w(e,r){const n=r.map(({id:{videoId:s},snippet:{title:t,channelTitle:o,thumbnails:{medium:{url:i}}}})=>`
    <li class="video-card">
      <a href="https://www.youtube.com/watch?v=${s}" target="_blank">
        <img class="video-img" src="${i}" alt="${t}">
      </a>
        <h3 class="video-text">${b(t,30)}</h3>
        <p class="video-text">${o}</p>
    </li>
  `).join("");e.insertAdjacentHTML("beforeend",n)}function b(e,r=100){return e.length>r?e.slice(0,r)+"...":e}function E(e){e.innerHTML=""}const L=document.querySelector(".form"),S=document.querySelector(".search-input"),l=document.querySelector(".search-btn"),u=document.querySelector(".video-list"),A=document.querySelectorAll(".container");let c="",d=1;L.addEventListener("submit",O);async function O(e){if(e.preventDefault(),a(l),c=S.value.trim(),!c){p("Please fill out the search field.");return}d=1,E(u);try{g(A);const r=await v(c,d);console.log(r),w(u,r.items)}catch(r){alert("Opps... Something went wrong. Try again later."),console.log(r)}finally{a(l)}}
//# sourceMappingURL=index.js.map
